"""Causal self-attention layouts for block-sparse attention.

The helpers in this module describe *sequence* structure only.  They make no
assumptions about a particular model, representation, or attention kernel and
can therefore be shared by any causal self-attention implementation.
"""

from collections.abc import Sequence

import torch
from torch import Tensor

from blksprs.utils.blksprs_tensor import BlksprsTensor


def build_causal_self_attention_layout(
        valid_lengths: Tensor | Sequence[int],
        sparsity_block_size: int,
) -> Tensor:
    """Build a lower-triangular block layout for padded causal self-attention.

    ``valid_lengths`` contains the unpadded length of each sequence.  The
    returned layout has one row and column per block up to the longest input;
    blocks outside an individual sequence's valid prefix are inactive.  A
    partial final block remains active and must be paired with the compact mask
    returned by :func:`build_causal_self_attention_mask`.

    The output is intentionally a dense block grid: this is the irreducible
    structural input required by the current BLK-SPRS Flash layout cache.  It
    is boolean and uses ``O(B * ceil(L / block_size)^2)`` memory, rather than a
    token-level attention matrix.
    """
    lengths = _normalise_valid_lengths(valid_lengths)
    _validate_block_size(sparsity_block_size)

    max_length = int(lengths.max().item()) if lengths.numel() else 0
    n_blocks = _ceil_div(max_length, sparsity_block_size)
    if n_blocks == 0:
        return torch.zeros(
            (lengths.numel(), 0, 0), dtype=torch.bool, device=lengths.device)

    block_positions = torch.arange(n_blocks, device=lengths.device)
    valid_blocks = block_positions.unsqueeze(0) < _ceil_div_tensor(
        lengths, sparsity_block_size).unsqueeze(1)
    lower_triangle = block_positions.unsqueeze(0) <= block_positions.unsqueeze(1)
    return (lower_triangle.unsqueeze(0)
            & valid_blocks.unsqueeze(2)
            & valid_blocks.unsqueeze(1)).contiguous()


def build_causal_self_attention_mask(
        valid_lengths: Tensor | Sequence[int],
        attention_layout: Tensor,
        sparsity_block_size: int,
) -> tuple[BlksprsTensor, Tensor]:
    """Build a compact causal/padding mask for a causal attention layout.

    The returned mask follows :func:`blksprs.ops.flash_attention`'s convention:
    ``True`` marks an ignored score.  Its accompanying layout contains only
    blocks that can contain a masked value: every diagonal block (for causal
    masking) and, for a partial final sequence block, that final query block's
    causal prefix (for padding rows).  It therefore avoids storing an identical
    all-false mask for every lower-triangular off-diagonal block.

    Args:
        valid_lengths: Unpadded sequence lengths, one per layout batch entry.
        attention_layout: Causal Q-K block layout generated by
            :func:`build_causal_self_attention_layout` or an equally shaped
            causal layout.  The compact mask layout is always a subset of it.
        sparsity_block_size: Side length of an individual sparse block.

    Returns:
        A pair ``(attention_mask, sparsity_layout_mask)`` suitable for the
        independent mask arguments of :func:`blksprs.ops.flash_attention`.
    """
    return _build_causal_attention_mask(
        valid_lengths,
        attention_layout,
        sparsity_block_size,
        window_size=None,
    )


def _build_causal_attention_mask(
        valid_lengths: Tensor | Sequence[int],
        attention_layout: Tensor,
        sparsity_block_size: int,
        window_size: int | None,
) -> tuple[BlksprsTensor, Tensor]:
    lengths = _normalise_valid_lengths(valid_lengths, device=attention_layout.device)
    _validate_block_size(sparsity_block_size)
    if attention_layout.dtype != torch.bool:
        raise TypeError("attention_layout must have dtype torch.bool")
    if attention_layout.dim() != 3:
        raise ValueError("attention_layout must have shape (batch, query_blocks, key_blocks)")
    if not attention_layout.is_contiguous():
        raise ValueError("attention_layout must be contiguous")
    if attention_layout.size(0) != lengths.numel():
        raise ValueError("valid_lengths and attention_layout must have the same batch size")
    if attention_layout.size(1) != attention_layout.size(2):
        raise ValueError("causal self-attention requires a square attention_layout")

    n_batches, n_blocks, _ = attention_layout.shape
    expected_blocks = _ceil_div(
        int(lengths.max().item()) if lengths.numel() else 0,
        sparsity_block_size,
    )
    if n_blocks != expected_blocks:
        raise ValueError("attention_layout does not match the longest valid length")

    expected_layout = build_causal_self_attention_layout(
        lengths, sparsity_block_size)
    if torch.any(attention_layout & torch.logical_not(expected_layout)):
        raise ValueError(
            "attention_layout contains blocks outside the valid causal prefix."
        )

    if n_blocks == 0:
        empty_layout = torch.zeros_like(attention_layout)
        empty_mask = torch.empty(
            (0, sparsity_block_size, sparsity_block_size),
            dtype=torch.bool,
            device=attention_layout.device,
        )
        return BlksprsTensor.wrap(empty_mask), empty_layout

    positions = torch.arange(n_blocks, device=attention_layout.device)
    diagonal = positions.unsqueeze(0) == positions.unsqueeze(1)
    if window_size is None:
        window_boundary = torch.zeros_like(diagonal)
    else:
        maximum_block_offset = _ceil_div(window_size - 1, sparsity_block_size)
        window_boundary = (
            positions.unsqueeze(1) - positions.unsqueeze(0) == maximum_block_offset
        )
    last_blocks = _ceil_div_tensor(lengths, sparsity_block_size) - 1
    has_partial_last_block = torch.remainder(lengths, sparsity_block_size) != 0
    final_partial_rows = (
        has_partial_last_block[:, None, None]
        & (positions[None, :, None] == last_blocks[:, None, None])
        & (positions[None, None, :] <= last_blocks[:, None, None])
    )
    sparsity_layout_mask = (
        attention_layout
        & (diagonal.unsqueeze(0) | window_boundary.unsqueeze(0) | final_partial_rows)
    ).contiguous()

    active_blocks = sparsity_layout_mask.nonzero(as_tuple=False)
    if active_blocks.numel() == 0:
        empty_mask = torch.empty(
            (0, sparsity_block_size, sparsity_block_size),
            dtype=torch.bool,
            device=attention_layout.device,
        )
        return BlksprsTensor.wrap(empty_mask), sparsity_layout_mask

    local_positions = torch.arange(
        sparsity_block_size, device=attention_layout.device)
    query_positions = (
        active_blocks[:, 1, None] * sparsity_block_size + local_positions[None, :]
    )
    key_positions = (
        active_blocks[:, 2, None] * sparsity_block_size + local_positions[None, :]
    )
    sequence_lengths = lengths[active_blocks[:, 0]]
    mask = (
        (key_positions[:, None, :] > query_positions[:, :, None])
        | (query_positions[:, :, None] >= sequence_lengths[:, None, None])
        | (key_positions[:, None, :] >= sequence_lengths[:, None, None])
    ).contiguous()
    if window_size is not None:
        mask = mask | (
            key_positions[:, None, :] < query_positions[:, :, None] - (window_size - 1)
        )
    return BlksprsTensor.wrap(mask), sparsity_layout_mask


def build_causal_window_self_attention_layout(
        valid_lengths: Tensor | Sequence[int],
        sparsity_block_size: int,
        window_size: int,
) -> Tensor:
    """Build a causal block layout restricted to a token-local window.

    ``window_size`` counts the current token, so a value of one permits only
    self-attention.  Boundary blocks are retained and refined by
    :func:`build_causal_window_self_attention_mask`; this keeps the layout
    block-sparse without changing the exact token-level window contract.
    """
    if not isinstance(window_size, int) or isinstance(window_size, bool):
        raise TypeError("window_size must be an integer")
    if window_size <= 0:
        raise ValueError("window_size must be positive")
    causal_layout = build_causal_self_attention_layout(
        valid_lengths, sparsity_block_size)
    n_blocks = causal_layout.size(1)
    positions = torch.arange(n_blocks, device=causal_layout.device)
    maximum_block_offset = _ceil_div(window_size - 1, sparsity_block_size)
    local_band = positions.unsqueeze(1) - positions.unsqueeze(0) <= maximum_block_offset
    return (causal_layout & local_band.unsqueeze(0)).contiguous()


def build_causal_window_self_attention_mask(
        valid_lengths: Tensor | Sequence[int],
        attention_layout: Tensor,
        sparsity_block_size: int,
        window_size: int,
) -> tuple[BlksprsTensor, Tensor]:
    """Build the compact causal/padding mask for local causal attention."""
    if not isinstance(window_size, int) or isinstance(window_size, bool):
        raise TypeError("window_size must be an integer")
    if window_size <= 0:
        raise ValueError("window_size must be positive")
    return _build_causal_attention_mask(
        valid_lengths,
        attention_layout,
        sparsity_block_size,
        window_size=window_size,
    )


def _normalise_valid_lengths(
        valid_lengths: Tensor | Sequence[int],
        device: torch.device | None = None,
) -> Tensor:
    lengths = torch.as_tensor(valid_lengths, device=device)
    if lengths.dim() != 1:
        raise ValueError("valid_lengths must be one-dimensional")
    if lengths.dtype == torch.bool or torch.is_floating_point(lengths):
        raise TypeError("valid_lengths must use an integer dtype")
    if torch.any(lengths < 0):
        raise ValueError("valid_lengths must be non-negative")
    return lengths.to(dtype=torch.long)


def _validate_block_size(sparsity_block_size: int) -> None:
    if not isinstance(sparsity_block_size, int) or isinstance(sparsity_block_size, bool):
        raise TypeError("sparsity_block_size must be an integer")
    if sparsity_block_size <= 0:
        raise ValueError("sparsity_block_size must be positive")


def _ceil_div(value: int, divisor: int) -> int:
    return (value + divisor - 1) // divisor


def _ceil_div_tensor(values: Tensor, divisor: int) -> Tensor:
    return torch.div(values + divisor - 1, divisor, rounding_mode="floor")
