[project]
name = "blksprs"
version = "2.3.1"
authors = [{ name = "Felix Schön", email = "schoen@kr.tuwien.ac.at" }]
description = "A lightweight library for operations on block-sparse matrices in PyTorch."
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
license-files = ["LICENSE.md"]
dependencies = ["torch >= 2.8.0"]

[project.urls]
"Homepage" = "https://github.com/FelixSchoen/blksprs"
"Bugtracker" = "https://github.com/FelixSchoen/blksprs/issues"

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-xdist",
    "pytest-cov",
    "coverage",
    "build",
    "matplotlib",
    "numpy",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["blksprs*"]

[tool.setuptools.package-data]
"*" = ["*.json", "*.conf"]

[tool.pytest.ini_options]
markers = [
    "benchmark: high-memory or high-runtime regression tests",
]
